name: Run Codebuild

on:
  push:
    branches:
      - main

env:
  REGION: eu-west-1
  PROJECT_NAME: test-github
  
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      # v1
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::304314271295:role/githubActionsTestRole
        role-session-name: MySessionName
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_2 }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_2 }}
#         aws-region: ${{ env.REGION }}
    - name: Git Clone
      uses: actions/checkout@v3
      with: 
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Run CodeBuild
      # v1.0.3
      uses: aws-actions/aws-codebuild-run-build@v1
      with:
        project-name: ${{ env.PROJECT_NAME }}
